#!/usr/bin/ruby

require 'rubygems'
require 'open4'
require 'sinatra'
require 'haml'
require 'yaml'

CONFIG = YAML::load_file(ARGV[0] || 'config.yml')

def do_magic
	result = plz_run_this CONFIG['command']
	parse_tests result
end

get '/code' do
	haml :code
end

get '/' do
	$results = do_magic
	haml :tests
end

def parse_tests result
	require "drivers/#{CONFIG['driver']}"
	Parser.parse_tests result[:stdout], result[:stderr], result[:exitcode]
end

def notice tests
	num_fail = tests[:failed].size
	notice = num_fail == 0 ? "All tests passed!" : "Fuuuuu! #{num_fail} tests have failed..."
end

def test_bar num_errors

	type = num_errors > 0 ? 'red' : 'green'

end

def plz_run_this command
	pid, stdin,stdout,stderr = Open4::popen4 command
	ignore,status = Process::waitpid2 pid
	{ :stdout => stdout.read, :stderr => stderr.read, :exitstatus => status.exitstatus }
end

