#!/usr/bin/ruby

require 'rubygems'
require 'open4'
require 'sinatra'
require 'haml'
require 'yaml'
require 'pp'

CONFIG = YAML::load_file(ARGV[0] || 'config.yml')

def do_magic
	result = plz_run_this CONFIG['command']
	parse_tests result
end

get '/code' do
	haml :code
end

get '/' do
	$results = do_magic
	haml :tests
end

def parse_tests result
	require "drivers/#{CONFIG['driver']}"
	Parser.parse_tests result[:stdout], result[:stderr], result[:exitcode]
end

def notice tests
	num_fail = tests.count { |t| not t[:passed] }
	num_fail == 0 ? "All tests passed!" : "Fuuuuu! #{num_fail} test(s) have failed..."
end

def test_bar tests
	tests.count {|x| not x[:passed] } > 0 ? 'red' : 'green'
end

def plz_run_this command
	pid, stdin,stdout,stderr = Open4::popen4 command
	ignore,status = Process::waitpid2 pid
	{ :stdout => stdout.read, :stderr => stderr.read, :exitstatus => status.exitstatus }
end

